-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/KobraKommander9/KobraVim/blob/main/lua/kobra/core/config/keymaps.lua
-- Add any additional keymaps here
