-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/KobraKommander9/KobraVim/blob/main/lua/kobra/core/config/options.lua
-- Add any additional options here
